---
title: "P8105 HW 5"
author: "Yuki Low (yl5503)"
date: "11/6/2023"
output:
  html_document:
    df_print: paged
---

Loading necessary libraries
```{r, message = FALSE}
library(tidyverse)
library(haven)
library(readxl)
library(janitor)
library(dplyr)
library(tidyr)
library(stringr)
library(broom)
library(purrr)
```

```{r, message = FALSE}
complete_data <- list.files(path = "data", pattern = "csv", full.names = TRUE)

combined_df <- purrr::map(complete_data, read_csv) %>% 
  bind_rows() %>% 
  mutate(arm = as.factor(if_else(row_number() %in% c(1:10), "control", "experimental")),
  ID = row_number ()) %>%
  relocate(arm, ID, .before = "week_1") %>%
  pivot_longer (cols = week_1:week_8, names_to = "week", values_to = "observation") %>%
  separate(week, into = c("prefix", "week"), sep = "_") %>%
  mutate(week = as.integer(week)) %>%
  select(-prefix)

head(combined_df)
```
```{r, message = FALSE}
ggplot(combined_df, aes(x = week, y = observation, group = ID, color = arm)) +
  geom_line() +
  labs(x = "Week", y = "Observation", color = "Arm", title = "Spaghetti Plot of Observations Over Time" )
```


